# This file is used for development purposes
name: disk_cache
channels:
  - defaults
dependencies:
  - python=3.8
  - twine  # Helps publishing packages on PyPI
  - pyyaml
  - pytest
  - pip:
      - build  # Creates built distributions (wheels)